AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'client/**/*'

Layout/LineLength:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
