---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/sign_in":
    post:
      summary: Sign in
      responses:
        '200':
          description: successful
  "/api/auth/sign_up":
    post:
      summary: Sign up
      responses:
        '200':
          description: successful
  "/api/entities":
    get:
      summary: list entities
      responses:
        '200':
          description: successful
    post:
      summary: create entity
      responses:
        '200':
          description: successful
  "/api/entities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show entity
      responses:
        '200':
          description: successful
    patch:
      summary: update entity
      responses:
        '200':
          description: successful
    put:
      summary: update entity
      responses:
        '200':
          description: successful
    delete:
      summary: delete entity
      responses:
        '200':
          description: successful
  "/api/tags":
    get:
      summary: list tags
      responses:
        '200':
          description: successful
    post:
      summary: create tag
      responses:
        '200':
          description: successful
  "/api/tags/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show tag
      responses:
        '200':
          description: successful
    patch:
      summary: update tag
      responses:
        '200':
          description: successful
    put:
      summary: update tag
      responses:
        '200':
          description: successful
    delete:
      summary: delete tag
      responses:
        '200':
          description: successful
  "/api/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
